README.md Creation
vmware-tanzu-labs/operator-builder pull request #152
Opened 2021-10-01 20:08 UTC by dghant1024

Adding this PR to resolve #91

2021-10-01 21:08 UTC, scottd018 requested changes

2021-10-01 21:08 UTC, scottd018 commented on internal/plugins/workload/v1/scaffolds/templates/readme.go
> +// func (p *Readme) Scaffold(fs machinery.Filesystem) error {
Removed commented fields

2021-10-01 21:08 UTC, scottd018 commented on internal/plugins/workload/v1/scaffolds/templates/readme.go
> +To install the custom resource/s for this operator:
resources

2021-10-01 21:08 UTC, scottd018 commented on internal/plugins/workload/v1/scaffolds/templates/readme.go
> +You can then test the operator by creating the sample manifest/s:
manifests

2021-10-01 21:08 UTC, scottd018 commented on internal/plugins/workload/v1/scaffolds/templates/readme.go
> +make uninstall
Remove this line

2021-10-01 21:11 UTC, scottd018 commented
In addition to small fixes in readme.go file, please fix:

- commit messages to conform with conventional commit format

2021-10-04 19:59 UTC, dghant1024 commented
Added suggested changes and merged

2021-10-04 20:37 UTC, dghant1024 commented on internal/plugins/workload/v1/scaffolds/templates/readme.go
> +// func (p *Readme) Scaffold(fs machinery.Filesystem) error {
done

2021-10-06 19:23 UTC, closed without merging